- name: webmin SYS265
  hosts: webmin
  become: true
  become_user: root
  vars:
    enable_firewalld: true
    uninstall_webmin: false
    ansible_os_family: "RedHat"
    install_utilities: true
  tasks:
  - name: add firewall rule
    firewalld:
      port: 10000/tcp
      permanent: true
      state: enabled
  roles:
  - roles/semuadmin.webmin
